DROP SCHEMA PUBLIC CASCADE;
CREATE SEQUENCE seq1 AS INTEGER START WITH 1;

CREATE TABLE CUSTOMER (
 id INT NOT NULL PRIMARY KEY,
 first_name VARCHAR(255),
 last_name VARCHAR(255),
 email VARCHAR(255),
 synniaeg VARCHAR(255),
 aadress VARCHAR (255)
);





